name: downloadToOneDrive
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Download url'
        required: true
      downloadTool:
        description: 'Download tool'
        required: true
        default: 'aria2'
        type: choice
        options:
          - aria2
          - curl
          - wget
          - yt-dlp
          - youtube-dl
      downloadToolOptions:
        description: 'Download tool options'
        required: false
      checkoutSHA256:
        description: 'Checkout SHA256'
        required: false
        default: 'true'
        type: boolean
      checkoutMD5:
        description: 'Checkout MD5'
        required: false
        default: 'flase'
        type: boolean

jobs:
  build:
    runs-on: windows-2022
    defaults:
      run:
        working-directory: C:\downloads
    steps:
    - name: Installation dependencies
      working-directory: .\
      run: |
        choco install rclone
        choco install ${{ github.event.inputs.downloadTool }}
        mkdir -p C:\downloads
    - name: Download
      run: |
        if('${{ github.event.inputs.downloadTool }}' -ne 'aria2'){${{ github.event.inputs.downloadTool }} ${{ github.event.inputs.downloadToolOptions }} '${{ github.event.inputs.url }}'}else{aria2c ${{ github.event.inputs.downloadToolOptions }} '${{ github.event.inputs.url }}'}
    - name: Output file sha256
      shell: bash
      run: |
        fileName=$(grep . *)
        if [[ ${{ github.event.inputs.downloadTool }} -eq 'true' ]]; then sha256sum * > $fileName.sha256 && cat $fileName.sha256 && sed -i 's/*//g' $fileName.sha256 fi
        if [[ ${{ github.event.inputs.downloadTool }} -eq 'true' ]]; then md5sum * > $fileName.md5 && cat $fileName.md5 && sed -i 's/*//g' $fileName.md5 fi
    - name: Upload all to OneDrive
      run: |
        mkdir -p $ENV:APPDATA\rclone
        echo '${{ secrets.RCLONE_CONFIG }}' >> $ENV:APPDATA\rclone\rclone.conf
        rclone copy ./ "OneDrive:/tmp" -P
        
